name: SK Telegram Bot deployment to Yandex Cloud Function

on:
    push:
        branches: [main]
    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: YC Function deploy
              id: sls-func
              uses: yc-actions/yc-sls-function@v2.12.0
              with:
                  yc-sa-json-credentials: ${{ secrets.YC_SA_JSON_CREDENTIALS }}
                  folder-id: "b1gavt7en80es8oo1hq2"
                  function-name: "sk-telegram-bot-ycf"
                  runtime: "golang121"
                  memory: "128Mb"
                  entrypoint: "main.YandexCFHandler"
                  service-account: "ajers1h0rubfdvd5hq4t"
                  secrets: |
                        SK_TELEGRAM_BOT_TOKEN=e6q0pan0cngvve7l3gmo/1.0/SK_TELEGRAM_BOT_TOKEN
                  include: ./
                  exclude: |
                      .github/**/*
                      .git/**/*
                      .git
                      .github
